### ISSUE TITLE
LGT8F328P Code changes

### ISSUE THREAD

**Issue by dogshome** [dennisMe2/CarbOnBal#5]
Hiya, I've built a couple of the balancers for my friends since the project came out. I have "engine ears", but can't balance a BMW airhead to get the best out of it. This brilliant project beats jiggling mechanical gauges and even die-hard beemer bikers can feel the advantage of this box of tricks. We are talking 1/32nd of a turn of adjustment screws being right or wrong.

I'm using the PCB and happened to get a Nano 'clone' by mistake this time (didn't know the differences). It compiles and works after redirecting to a compatible EEPROM library and commenting out 'put' and 'get' commands. 'read', 'write' and 'clear' have been implemented and do work.
It's only (ha!) the 'settings' structure that is saved and reloaded in this way. I am not capable of creating my own library complex function like that, so wonder if I can handball it by doing it a setting at a time? Write setting.prameter1, Write setting.parameter2 etc. Thing is, how do I see the setting structure from the code? I am used to PLCs that list them with values in a table like excel. There only seem to be about a dozen of them.

EDIT: Found in Globals! D'oh!

Rough as you like-
//saves our settings struct
void actionSaveSettings() {
	//EEPROM.put(0, versionUID);  //only saves changed bytes!
	//EEPROM.put(1, settingsOffset);
	//EEPROM.put(settingsOffset, settings);  //only saves changed bytes!
  //LGT8F32 has no EEPROM.put support yet
  EEPROM.write(0,versionUID);
  EEPROM.write(1,settingsOffset);
  EEPROM.write(2,settings.silent);
  EEPROM.write(3,settings.advanced);
  EEPROM.write(4,settings.splashScreen);//bool is 8 bits on Arduino
  EEPROM.write(5,settings.cylinders);
  EEPROM.write(6,settings.master);
  EEPROM.write(7,settings.button1);
  EEPROM.write(8,settings.button2);
  EEPROM.write(9,settings.button3);
  EEPROM.write(10,settings.contrast);
  EEPROM.write(11,settings.brightness);
  EEPROM.write(12,settings.graphType);
  EEPROM.write(13,settings.rpmDamping);
  EEPROM.write(14,settings.units);
  EEPROM.write(15,settings.zoom);
  EEPROM.write(16,settings.calibrationMax);
  EEPROM.write(17,settings.damping);
	delay(100);  //eeprom settle time

There is no EEPROM as such in these on flash emulation, so the EEPROM checks and moving to suit failed bytes will be ignored.

For 'get':
    settings.silent = EEPROM.read(2);
    settings.advanced = EEPROM.read(3);

etc....

(NEWB!)

**Comment by dennisMe2** [comment]
Sorry I didn't see this! Good thing you found it. Thanks for the positive feedback.
